# Hyprlock Configuration

background {
    monitor =
    path = screenshot # Captures l'écran comme fond
    blur_passes = 2
    blur_size = 10
    contrast = 0.8
    brightness = 0.8
    vibrancy = 0.1
    vibrancy_darkness = 0.0
}

# Nom
label {
    monitor =
    text = Louis
    text_align = center
    font_size = 32
    font_family = JetBrains Mono
    position = 0, 40
    halign = center
    valign = center
    shadow_passes = 3
    shadow_boost = 1.0
    color = rgba(180, 180, 180, 0.8)
}

# Horloge
label {
    monitor =
    text = $TIME
    text_align = center
    font_size = 120
    font_family = JetBrains Mono
    position = 0, 140
    halign = center
    valign = center
    shadow_passes = 5
    shadow_boost = 1.2
    color = rgba(200, 200, 200, 1.0)
}

# Champ de mot de passe
input-field {
    monitor =
    size = 300, 70
    outline_thickness = 4
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(80, 80, 80)
    inner_color = rgb(50, 50, 50)
    font_color = rgb(200, 200, 200)
    check_color = rgb(100, 200, 100)
    fail_color = rgb(220, 50, 50)
    fail_text = $ATTEMPTS tentative(s)
    capslock_color = rgb(255, 150, 0)
    placeholder_text = Mot de passe...
    hide_input = false
    rounding = -1
    check_rounding = -1
    position = 0, -40
    halign = center
    valign = center
    shadow_passes = 5
    shadow_boost = 1.2
    font_family = JetBrains Mono
    font_size = 18
}
