preload = $HOME/.config/hypr/wallpapers/hypr-Meptl.png
preload = $HOME/.config/hypr/wallpapers/hypr-corndog.png
preload = $HOME/.config/hypr/wallpapers/hypr-srev.png
preload = $HOME/.config/hypr/wallpapers/hypr-end_4.png
preload = $HOME/.config/hypr/wallpapers/hypr-Kath.png

# New wallpapers
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Anime-Girl-Night-Sky.jpg
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Anime-Girl-Rain.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Anime-Japan-Street.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Anime-Room.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/anime-wall.jpg
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Backyard.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Balcony-ja.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Cartoon.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Classroom.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Courtside-Sunset.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/CuteCat.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Dreamy-Aesthetic-Home-Under-Moonlight.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Fantasy-Japanese-Street.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Fantasy-Landscape3.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Fantasy-Lanscape-Night.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Fantasy_-_Sunset.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Game-GTA.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Garage.jpg
preload = $HOME/.config/hypr/wallpapers/newwallpapers/girl-laying-down.jpg
preload = $HOME/.config/hypr/wallpapers/newwallpapers/IT_guy.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Lady.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Linux-user-Room.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Lofi-Room.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Manga-Girl-Rain.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Messy-Room.jpg
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Minimal_Squares.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Nature_-_Concept_Butterflies.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Pastel-Window.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Purple-bedroom-monsters.jpg
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Purple-night-sky-river.jpg
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Purple-night-street-view.jpg
preload = $HOME/.config/hypr/wallpapers/newwallpapers/rain-house-tree.jpg
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Relaxed_Mario.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Staircase.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Sun-Setting-Horizon.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Techno-Geek.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Under_Starlit_Sky.png
preload = $HOME/.config/hypr/wallpapers/newwallpapers/Video_Game_-_The_Blackstreets.jpeg

wallpaper = eDP-1,$HOME/.config/hypr/wallpapers/hypr-end_4.png

splash = false
